ssdsd/recipe-app-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: redirect("recipes#index"), as: :authenticated_root
  end
  unauthenticated do
    root to: redirect("/public_recipes"), as: :unauthenticated_root
  end

  match "/public_recipes", to: "recipes#index", via: :get

  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  resources :users
end

ssdsd/recipe-app-dev/app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    <div class="ms-3">
      <strong><%= notice %></strong>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    <div class="ms-3">
      <strong><%= alert %></strong>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

ssdsd/recipe-app-dev/app/views/shared/_navbar.html.erb
<script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js" type="text/javascript"></script>
<nav class="navbar navbar-expand-lg navbar-light p-3" style="background: yellow;">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to authenticated_root_path, class: "navbar-brand" do %>
        <h3 class="text-uppercase mb-0">🥣Recipe<span class="text-danger">App</span></h3>
      <% end %>
    <% else %>
      <%= link_to unauthenticated_root_path, class: "navbar-brand" do %>
        <h3 class="text-uppercase">🥣Recipe<span class="text-danger">App</span></h3>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Home", authenticated_root_path, class: "nav-link fs-5" %>
          <% else %>
            <%= link_to "Home", unauthenticated_root_path, class: "nav-link fs-5" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Public Recipes", "/public_recipes", class: "nav-link fs-5" %>
          <% end %>
        </li>
        <li class="nav-item" style="padding:10px">
          <% if user_signed_in? %>
            <input id="input-search" style="margin: auto;height: 100%;border-radius: 5px;" type="text" placeholder="Search.." >
          <% end %>
        </li>
        <li class="nav-item" style="padding:10px">
          <% if user_signed_in? %>
            <a class="btn btn-primary" onclick="onSearch()">Search</a>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "My Ingredients", foods_path, class: "dropdown-item" %>
              </li>
              <li><%= link_to "My Recipes", recipes_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link fs-5" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link fs-5" %>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<script>
  function onSearch(){
    let value = document.getElementById('input-search').value

    window.location.href='/recipes?search='+value
  }
</script>