ssdsd/recipe-app-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: redirect("recipes#index"), as: :authenticated_root
  end
  unauthenticated do
    root to: redirect("/public_recipes"), as: :unauthenticated_root
  end

  match "/public_recipes", to: "recipes#index", via: :get

  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  resources :users
end

ssdsd/recipe-app-dev/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
  validates :user, presence: true

  def total_food_items
    recipe_foods.count
  end

  def total_price_for_food_items
    sum = 0
    recipe_foods.each do |item|
      sum += item.quantity * item.food.price
    end
    sum
  end
end

ssdsd/recipe-app-dev/app/controllers/recipes_controller.rb
require 'securerandom'
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    if !params[:search]
      @recipes = Recipe.all
    else
      @recipes = Recipe.where("name LIKE ?", "%"+params[:search]+"%")
      
    end
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.file_path = save_file(params[:recipe][:image])
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end
  def save_file(file)
    if file
      fileName = SecureRandom.uuid
      file_path = Rails.root.join('app/assets/images',fileName+file.original_filename)
      File.open(file_path, 'wb') do |f|
        f.write(file.read)
      end
      fileName+file.original_filename
    end
  end
  def edit
    
  end

  def update
    respond_to do |format|
      if params[:recipe][:image]
        @recipe.file_path = save_file(params[:recipe][:image])
      end
      
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

ssdsd/recipe-app-dev/app/helpers/recipes_helper.rb
module RecipesHelper
end

ssdsd/recipe-app-dev/app/views/recipes/_form.html.erb
<%= form_with(model: @recipe) do |form| %>
  <% if @recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3 w-50">
    <%= form.label :name, style: "display: block", class: "fs-5" %>
    <%= form.text_field :name, class: "form-control fs-5" %>
  </div>
  <div class="mb-3 w-50">
    <%= form.label :preparation_time, style: "display: block", class: "fs-5" %>
    <%= form.text_field :preparation_time, class: "form-control fs-5", placeholder: "How long does it take to prepare(1 hour or 30 mins)" %>
  </div>
  <div class="mb-3 w-50">
    <%= form.label :cooking_time, style: "display: block", class: "fs-5" %>
    <%= form.text_field :cooking_time, class: "form-control fs-5", placeholder: "How long does it take to cook(1 hour or 30 mins)" %>
  </div>
  <div class="mb-3 w-50">
    <%= form.label :description, style: "display: block", class: "fs-5" %>
    <%= form.text_area :description, class: "form-control fs-5" , size: "50x8", placeholder: "Describe how the meal is prepared" %>
  </div>
  <div class="mb-3 form-check">
    <%= form.check_box :public, class: "form-check-input fs-5" %>
    <%= form.label :public, style: "display: block", class: "form-check-label fs-5" %>
  </div>
  <div class="mb-3 form-check">
    Upload Image: 
    <%= form.file_field :image %>  <%= @recipe.file_path %>
   
  </div>
  <div>
    <%= form.submit class: "btn btn-primary fs-5" %>
  </div>
<% end %>

ssdsd/recipe-app-dev/app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="card w-75 mx-auto mb-3">
  <div class="card-body d-flex justify-content-between align-items-start gap-5">
    <div>
      <h4 class="card-title"><%= recipe.name %></h4>
      <p class="text-muted">By: <%= recipe.user.name %></p>
    </div>
    <div>
      <% if request.path == "/public_recipes" %>
        <p>Total Food Items: <%= recipe.total_food_items %></p>
        <p>Total Price: $<%= recipe.total_price_for_food_items %></p>
      <% elsif request.path == "/recipes" %>
        <p>Preparation time: <%= recipe.preparation_time %></p>
        <p>Cooking time: <%= recipe.cooking_time %></p>
      <% end %>
      <div class="d-flex gap-3 mt-3">
        <%= link_to "Details", recipe, class: "btn btn-secondary" %>
        <% if current_user == recipe.user && request.path == "/recipes" %>
          <%= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
          <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-info", style: "text-decoration: none;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

ssdsd/recipe-app-dev/app/views/recipes/_shopping_list.html.erb
<tr>
  <th scope="row"><%= index + 1 %></th>
  <td><%= ingredient.food.name %></td>
  <td><%= ingredient.quantity - ingredient.food.quantity %> <%= ingredient.food.measurement_unit %></td>
  <td>$<%=ingredient.food.price * (ingredient.quantity - ingredient.food.quantity) %></td>
</tr>

ssdsd/recipe-app-dev/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

<script>
console.log('dsfsdf')
CKEDITOR.disableAutoInline = true;
  CKEDITOR.config.toolbar = [{
	name: 'editing',
	items: ['Scayt', 'Cut', 'Copy', 'Paste', 'Bold', 'Italic', 'Underline']
}];

CKEDITOR.replace('recipe_description', {
  scayt_autoStartup: true,
  grayt_autoStartup: true
});
</script>

ssdsd/recipe-app-dev/app/views/recipes/index.html.erb
<% if request.path == '/public_recipes' %>
  <h1 class="text-center mb-3">Public Recipes</h1>
  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <% if recipe.public %>
        <%= render recipe %>
      <% end %>
    <% end %>
  </div>
<% elsif request.path == '/recipes' %>
  <div class="d-flex justify-content-between align-items-center w-75 mx-auto">
    <h1>My Recipes</h1>
    <%= link_to "New recipe", new_recipe_path, class: "btn btn-primary" %>
  </div>
  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <% if recipe.user == current_user %>
        <%= render recipe %>
      <% end %>
    <% end %>
    <% if current_user.recipes.empty? && !@recipes.empty? %>
      <p class="text-center fs-4"> Sorry, no recipes available.</p>
    <% end %>
  </div>
<% end %>
<% if @recipes.empty? %>
  <p class="text-center fs-4"> Sorry, no recipes available.</p>
<% end %>

ssdsd/recipe-app-dev/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

<script>
console.log('dsfsdf')
CKEDITOR.disableAutoInline = true;
  CKEDITOR.config.toolbar = [{
	name: 'editing',
	items: ['Scayt', 'Cut', 'Copy', 'Paste', 'Bold', 'Italic', 'Underline']
}];

CKEDITOR.replace('recipe_description', {
  scayt_autoStartup: true,
  grayt_autoStartup: true
});
</script>

ssdsd/recipe-app-dev/app/views/recipes/show.html.erb
<div class="w-75 mx-auto">
  <div class="d-flex justify-content-between align-items-center gap-3">
    <% unless user_signed_in? %>
      <%= link_to "<<- Back to Recipes", unauthenticated_root_path %>
    <% else %>
      <%= link_to "<<- Back to Recipes", recipes_path %>
    <% end %>
    <% if current_user == @recipe.user %>
      <%= button_to "Delete Recipe", @recipe, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
  <div class="text-center my-4">
    <h1 class="text-center"><%= @recipe.name %></h1>
  </div>
  <div class="recipe-details d-flex justify-content-between">
    <div>
      <p class="mb-3">Preparation Time: <%= @recipe.preparation_time %></p>
      <p class="mb-3">Cooking Time: <%= @recipe.cooking_time %></p>
      <p class="text-decoration-underline">Steps To Prepare Meal</p>
      <p><%= @recipe.description.html_safe %></p>
    </div>
    <div>
      <% if @recipe.file_path %>
        <%= image_tag(@recipe.file_path) %>
      <% end %>
    </div>
    <div class="public">
      <%= form_with model: @recipe, url: recipe_path(@recipe), method: :patch do |form| %>
        <div class="form-check form-switch">
          <% if current_user == @recipe.user %>
            <%= form.check_box :public, class: ["form-check-input", "bg-success": @recipe.public], onchange: "this.form.submit()" %>
          <% else %>
            <%= form.check_box :public, class: ["form-check-input", "bg-success": @recipe.public], onchange: "this.form.submit()", disabled: true %>
          <% end %>
          <label class="form-check-label" for="flexSwitchCheckChecked">
            Public Recipe</label>
        </div>
      <% end %>
    </div>
  </div>
  <% if user_signed_in? && @recipe.user == current_user %>
    <div class="d-flex justify-content-between align-items-center mt-5 mb-3">
      <!-- Button to trigger shoppingList modal -->
      <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#shoppingList">
        Generate Shopping List
      </button>
      <!-- Button to trigger addIngredient modal -->
      <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#addIngredient">
        Add Ingredient
      </button>
    </div>
    <!-- addIngredient Modal -->
    <%= form_with model: RecipeFood, url: recipe_recipe_foods_path(@recipe) do |form| %>
      <div class="modal fade" id="addIngredient" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Ingredient</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= render "recipe_foods/form", form: form %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <div class="submit-btn">
                <%= form.submit  "Add Recipe Food", class: "btn btn-primary btn-block"  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <!-- shoppingList Modal -->
    <div class="modal fade" id="shoppingList" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <%# <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add Ingredient</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div> %>
          <div class="modal-body">
            <h3 class="text-center">Shopping List</h3>
            <div class="mt-4 px-5 d-flex justify-content-between align-items-center">
              <p>Amount of food items to buy: <%= current_user.shopping_list[0] %></p>
              <p>Total value of food needed: <%= current_user.shopping_list[1] %></p>
            </div>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Ingredients</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Price</th>
                </tr>
              </thead>
              <tbody>
                <% current_user.shopping_list[2].each_with_index do |ingredient, index| %>
                  <%= render "shopping_list", ingredient: ingredient, index: index %>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <div class="submit-btn">
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% unless user_signed_in? %>
    <h5 class="mt-4">Ingredients</h5>
  <% end %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Ingredients</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <% if @recipe.user == current_user %>
          <th scope="col" class="text-center">Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each_with_index do |recipe_food, index| %>
        <%= render recipe_food, index: index %>
      <% end %>
    </tbody>
  </table>
  <% if @recipe.recipe_foods.empty? %>
    <p class="fs-4 text-center">Whoops! No ingredient found.</p>
  <% end %>
</div>
<style>
img{
  max-width: 15rem;
  max-height: 15rem;
}

</style>