ssdsd/recipe-app-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: redirect("recipes#index"), as: :authenticated_root
  end
  unauthenticated do
    root to: redirect("/public_recipes"), as: :unauthenticated_root
  end

  match "/public_recipes", to: "recipes#index", via: :get

  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  resources :users
end

ssdsd/recipe-app-dev/app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_or_equal_to: 0 }
end

ssdsd/recipe-app-dev/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

ssdsd/recipe-app-dev/app/helpers/foods_helper.rb
module FoodsHelper
end

ssdsd/recipe-app-dev/app/views/foods/_food.html.erb
<tr>
  <th scope="row"><%= index + 1 %></th>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td class="text-center"><%= button_to "Delete", food_path(food), method: :delete, class: "btn btn-danger" %></td>
</tr>

ssdsd/recipe-app-dev/app/views/foods/_form.html.erb
<%= form_with model: food, url: foods_path, local: true do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ssdsd/recipe-app-dev/app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

ssdsd/recipe-app-dev/app/views/foods/index.html.erb
<div class="foods_header d-flex justify-content-between align-items-center">
  <h1>Foods</h1>
  <%= link_to "New food", new_food_path, class: "btn btn-primary" %>
</div>
<table class="table table-bordered mt-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ingredients</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each_with_index do |food, index| %>
      <%= render food, index: index %>
    <% end %>
  </tbody>
</table>
<% if @foods.empty? %>
  <p class="fs-4 text-center">Sorry, no food found.</p>
<% end %>

ssdsd/recipe-app-dev/app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

ssdsd/recipe-app-dev/app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>